FROM ghcr.io/pesader/toolbxes:base

ENV VERSION=36 NAME=base

LABEL name = $NAME \
      version = $VERSION \
      description = "Container for all curricular Unicamp activities" \
      author = "Pedro Sader Azevedo <pedro.azevedo@students.ic.unicamp.br>" \
      source = "https://github.com/pesader/toolboxes"

# enable additional software repositories
RUN dnf copr enable -y marcusmueller/sc-im

# upgrade and install packages
COPY packages /
RUN dnf upgrade -y --refresh \
    && dnf install -y $(<packages) \
    && dnf clean all -y \
    && rm /packages
