FROM ghcr.io/pesader/toolbxes:base

ENV VERSION=36 NAME=base

LABEL name = $NAME \
      version = $VERSION \
      description = "Container for all LKCAMP activities" \
      author = "Pedro Sader Azevedo <pedro.azevedo@students.ic.unicamp.br>" \
      source = "https://github.com/pesader/toolboxes"

# upgrade and install packages
COPY packages /
RUN dnf upgrade -y --refresh \
    && dnf install -y $(<packages) \
    && dnf clean all -y \
    && rm /packages

# install correct hugo version
RUN wget https://github.com/gohugoio/hugo/releases/download/v0.92.2/hugo_0.92.2_Linux-64bit.tar.gz \
    && mkdir hugo_0.92.2_Linux-64bit \
    && tar -xvzf ./hugo_0.92.2_Linux-64bit.tar.gz hugo \
    && mv hugo /usr/bin/ \
    && rm hugo_0.92.2_Linux-64bit.tar.gz
